run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - noctx
    - exportloopref

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - (io.Closer).Close
      - (net.Listener).Close
      - (net.Conn).Close
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: lem/server,lem/agent
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose
        - noctx
  max-issues-per-linter: 50
  max-same-issues: 10
